name: Testing

on:
  push:
  pull_request:
    branches: [ 2.x ]
  schedule:
    - cron: '0 13 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.9, 3.12.6, 3.13.0]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
      - name: Start RabbitMQ
        run: |
          docker build -t amqpstormdev ./docker/
          docker run -d --hostname rmq.eandersson.net --name amqpstormdev -p 5671:5671 -p 5672:5672 -p 15671:15671 -p 15672:15672 amqpstormdev
          docker cp amqpstormdev:/etc/rabbitmq/ssl/ ./amqpstorm/tests/resources/
          docker exec amqpstormdev wait-for-rabbitmq
          echo "RabbitMQ Version: $(docker exec amqpstormdev rabbitmqctl --version)"
          docker exec amqpstormdev rabbitmqctl add_user 'amqpstorm' '2a55f70a841f18b'
          docker exec amqpstormdev rabbitmqctl -p / set_permissions 'amqpstorm' '.*' '.*' '.*'
          docker exec amqpstormdev rabbitmqctl set_user_tags amqpstorm administrator
          nc -zv rmq.eandersson.net 5671  || exit 1
          nc -zv rmq.eandersson.net 5672  || exit 1
          nc -zv rmq.eandersson.net 15671 || exit 1
          nc -zv rmq.eandersson.net 15672 || exit 1
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Test with pytest
        run: |
          pytest
